// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJFr48Vygbi99NdcaqvBWP_gzI5Gifi5g',
    appId: '1:306002382003:web:645d6d9c303df667e8b4c6',
    messagingSenderId: '306002382003',
    projectId: 'modern-login-fe81e',
    authDomain: 'modern-login-fe81e.firebaseapp.com',
    storageBucket: 'modern-login-fe81e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxY32vd3418J-4B9JYt5yLP5PfipsPjVs',
    appId: '1:306002382003:android:e961e0dd20581091e8b4c6',
    messagingSenderId: '306002382003',
    projectId: 'modern-login-fe81e',
    storageBucket: 'modern-login-fe81e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaM_l7KL0hBzA98EZSyAaTDWiYba1C8mY',
    appId: '1:306002382003:ios:d87325633e119f08e8b4c6',
    messagingSenderId: '306002382003',
    projectId: 'modern-login-fe81e',
    storageBucket: 'modern-login-fe81e.appspot.com',
    iosBundleId: 'com.example.modernLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaM_l7KL0hBzA98EZSyAaTDWiYba1C8mY',
    appId: '1:306002382003:ios:150d1fbbb1051978e8b4c6',
    messagingSenderId: '306002382003',
    projectId: 'modern-login-fe81e',
    storageBucket: 'modern-login-fe81e.appspot.com',
    iosBundleId: 'com.example.modernLogin.RunnerTests',
  );
}
